version: '3'

services:
  parser:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: #volume to consume all zips from
      - /Users/Nursultan/volumes/test/zips:/app/zips
    depends_on: # waiting for db up
      - master
      - segment
    networks:
      - backend

  gpfdist:
    build: gp/gpfdist
    volumes:
      - /Users/Nursultan/volumes/test/czips:/app/czips/
    command: /usr/lib/gpdb/bin/gpfdist -d /app/czips/ -p 8888
    networks:
        - backend

  #gp for itest
  master:
    build: gp/gpdb/stable
    links:
      - segment
    networks:
      - backend

  segment:
    build: gp/gpdb/stable
    entrypoint: gpdb-seg-entrypoint.sh
    networks:
      - backend




# common network
networks:
  backend: